sudo: required
services:
  - docker

before_install:
  - docker build -t spoorthi54/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true spoorthi54/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-905418214001"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
